[profile.default]
src = 'src'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidity-parser/=node_modules/truffle-flattener/node_modules/@solidity-parser/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'truffle/=node_modules/truffle/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config